apiVersion: v1
kind: Pod
metadata:
  name: appcoup
spec:
  containers:
  - name: generator
    image: 172.30.1.1:5000/appcoup/generator:latest
    volumeMounts:
    - name: data
      mountPath: "/tmp/out"
  - name: echo
    image: 172.30.1.1:5000/appcoup/echo:latest
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: data
      mountPath: "/tmp/in"
  volumes:
  - name: data
    emptyDir: {}
